# Numpy

In [ ]:
import numpy as np

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [ ]:
a = np.zeros(100)

#### 2.Создать вектор размера 100, заполненный единицами

In [ ]:
b = np.ones(100)

#### 3.Создать вектор размера 100, заполненный числом 3

In [ ]:
c = np.ones(100) * 3

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [ ]:
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 5. Поменять 2 строки в матрице

In [ ]:
a = np.random.randint(0, 10, size=(3, 3))
a

array([[4, 3, 4],
       [4, 1, 9],
       [1, 3, 8]])

In [ ]:
n = 0
m = 1
a[[n, m]] = a[[m, n]]
a

array([[4, 1, 9],
       [4, 3, 4],
       [1, 3, 8]])

#### 6. Создать вектор со значениями от 10 до 100

In [ ]:
b = np.arange(10, 100)

#### 7. Развернуть вектор (первый становится последним)

In [ ]:
a = np.arange(10)
np.flip(a)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [ ]:
a = np.arange(0, 16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [ ]:
a = np.arange(1, 6)
z = np.zeros(3 * len(a)).reshape(len(a), 3)
np.hstack((a.reshape(len(a), 1), z)).reshape(-1)

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.,
       0., 0., 0.])

#### 10. Создать 3x3 единичную матрицу

In [ ]:
a = np.eye(3, 3)

#### 11. Создать массив 3x3x3 со случайными значениями

In [ ]:
a = np.random.random((3, 3, 3))

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [ ]:
a = np.random.random((10, 10))
print(np.max(a))
print(np.min(a))

0.9911997450151233
0.006272280498108351


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [ ]:
a = np.random.random(30)
np.mean(a)

0.49613313450526253

#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [ ]:
n = 5
a = np.zeros((n, n))
a[0] = 1
a[n-1] = 1
a[:, 0] = 1
a[:, n-1] = 1
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [ ]:
np.row_stack((np.zeros(5), np.column_stack((np.diag([1, 2, 2, 4]), np.zeros(4)))))

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [ ]:
a = np.zeros((8, 8))
a[1::2, 1::2] = 1
a[::2, ::2] = 1
a.astype(int)

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [ ]:
indices = np.arange(0, 6*7*8).reshape(6, 7, 8)
x, y, z = np.where(indices == 99) # так как отсчет начинается с 0
print(x, y, z)

[1] [5] [3]


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [ ]:
row_a = np.tile([1, 0], 4)
a = np.row_stack((row_a, np.flip(row_a)))
a = np.tile(a, (4, 1))
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 24. Есть генератор, сделать с его помощью массив

In [ ]:
def square(n):
    for i in range(1, n):
        yield i ** 2

In [ ]:
a = np.fromiter(square(4), dtype=int)
a

array([1, 4, 9])

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [ ]:
a = np.linspace(0, 1, 10)
a

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 26. Отсортировать вектор

In [ ]:
a = np.random.random(10)
np.sort(a)
a

array([0.07720236, 0.33853878, 0.58832761, 0.78793392, 0.48127668,
       0.77215789, 0.72393537, 0.70990582, 0.67675725, 0.19705379])

#### 27. Проверить, одинаковы ли 2 numpy массива

In [ ]:
a = np.arange(10)
b = np.arange(10)
c = np.random.randint(0, 10, size=(10))

In [ ]:
print(np.array_equal(a, b))
print(np.array_equal(b, c))

True
False


#### 28. Сделать массив неизменяемым

In [ ]:
a = np.arange(10)
a.flags.writeable = False

In [ ]:
a[1] = 0

ValueError: assignment destination is read-only

#### 29. Найти n наибольших значений в массиве

In [ ]:
n = 5
a = np.random.random(10)
np.sort(a)[-n:]

array([0.56106276, 0.73094816, 0.78655736, 0.85027346, 0.92164162])

#### 30. Заменить максимальный элемент на ноль

In [ ]:
a[np.argmax(a)] = 0
a

array([0.47774815, 0.85027346, 0.05489475, 0.39898928, 0.78655736,
       0.        , 0.49670836, 0.40328877, 0.73094816, 0.56106276])

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [ ]:
x = np.random.random(5)
y = np.random.random(5)

c = 1/(np.repeat(x, 5).reshape(5, 5) - y)
c

array([[  6.23716768,   8.4252634 ,   3.24930487,  -2.68049675,
         -4.5122639 ],
       [  1.59360263,   1.70686192,   1.29042589,  10.62533932,
          4.07229834],
       [  2.58818975,   2.90080492,   1.87336297,  -6.801614  ,
        226.09047954],
       [  1.57401145,   1.68440666,   1.27754981,   9.81113242,
          3.94676651],
       [-20.79168798, -11.14396412,  10.06716753,  -1.71971854,
         -2.32534578]])

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [ ]:
for i in np.sctypeDict.values():
    try:
        print(f"{i} max: {np.finfo(i).max} min: {np.finfo(i).min}")
    except ValueError:
        pass

<class 'numpy.float16'> max: 65504.0 min: -65504.0
<class 'numpy.float16'> max: 65504.0 min: -65504.0
<class 'numpy.float16'> max: 65504.0 min: -65504.0
<class 'numpy.float32'> max: 3.4028234663852886e+38 min: -3.4028234663852886e+38
<class 'numpy.float32'> max: 3.4028234663852886e+38 min: -3.4028234663852886e+38
<class 'numpy.float64'> max: 1.7976931348623157e+308 min: -1.7976931348623157e+308
<class 'numpy.float64'> max: 1.7976931348623157e+308 min: -1.7976931348623157e+308
<class 'numpy.float64'> max: 1.7976931348623157e+308 min: -1.7976931348623157e+308
<class 'numpy.longdouble'> max: 1.7976931348623157e+308 min: -1.7976931348623157e+308
<class 'numpy.longdouble'> max: 1.7976931348623157e+308 min: -1.7976931348623157e+308
<class 'numpy.longdouble'> max: 1.7976931348623157e+308 min: -1.7976931348623157e+308
<class 'numpy.complex128'> max: 1.7976931348623157e+308 min: -1.7976931348623157e+308
<class 'numpy.complex64'> max: 3.4028234663852886e+38 min: -3.4028234663852886e+38
<class 'n

#### 34. Напечатать все значения в массиве

In [ ]:
for i in np.array([1, 2, 3]):
    print(i)

1
2
3


#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
n = 0.43
a = np.random.random((4, 4))
print(a)
sth = np.abs((a - n)).argmin()
# a[sth // 4, sth % 4] or
a.reshape(-1)[sth]

[[0.12366214 0.77669048 0.91424388 0.54084781]
 [0.33150222 0.12219232 0.11705504 0.67583526]
 [0.09889895 0.96745649 0.35587225 0.19431172]
 [0.44341139 0.76504013 0.0051387  0.54677625]]


0.44341139270303576

#### 36. Преобразовать массив из float в int

In [ ]:
a.astype(int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [ ]:
for i, el in np.ndenumerate(a):
    print(i, el)

(0, 0) 0.12366214149480481
(0, 1) 0.776690475473209
(0, 2) 0.9142438837934341
(0, 3) 0.5408478114702071
(1, 0) 0.3315022185276074
(1, 1) 0.12219232267059499
(1, 2) 0.11705504486358764
(1, 3) 0.6758352558720135
(2, 0) 0.09889894794899978
(2, 1) 0.9674564898535678
(2, 2) 0.35587225029173775
(2, 3) 0.19431171794114388
(3, 0) 0.44341139270303576
(3, 1) 0.7650401299890821
(3, 2) 0.005138697572116824
(3, 3) 0.546776248492382


#### 38. Случайно расположить p элементов в 2D массив

In [ ]:
p = 6
a = np.random.random(p).reshape((2, p//2))
a

array([[0.39361775, 0.80757956, 0.75746845],
       [0.17882759, 0.61930042, 0.87595315]])

#### 39. Отнять среднее из каждой строки в матрице

In [ ]:
a - a.mean()

array([[-0.21184007,  0.20212174,  0.15201063],
       [-0.42663023,  0.0138426 ,  0.27049533]])

#### 40. Отсортировать матрицу по n-ому столбцу

In [ ]:
a = np.random.randint(0, 10, size=(4, 3))
n = 0
a[a.transpose()[n].argsort()]

array([[0, 8, 5],
       [5, 1, 1],
       [5, 5, 7],
       [9, 4, 1]])

#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [ ]:
b = np.array([[0, 1, 0], [0, 2, 0], [0, 4, 0]])
b.any(axis=0)

array([False,  True, False])

#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [ ]:
a = np.array([1, 3, 4, 3, 25])
indices = [4, 3, 0]
a[indices] += 1
a

array([ 2,  3,  4,  4, 26])

#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [ ]:
w, h = 3, 4
a = np.random.randint(0, 10, size=(w, h, 3))
np.unique(a.reshape(w*h, 3), axis=0)

array([[0, 2, 6],
       [0, 9, 1],
       [1, 7, 7],
       [2, 8, 2],
       [3, 8, 0],
       [3, 8, 5],
       [4, 2, 4],
       [4, 7, 5],
       [5, 3, 7],
       [6, 1, 2],
       [7, 7, 8],
       [9, 4, 4]])

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [ ]:
a = np.random.randint(0, 10, size=(3, 3, 3, 3))
np.sum(a, axis=(2, 3))

array([[30, 36, 40],
       [27, 36, 40],
       [51, 42, 39]])