# Numpy

In [2]:
import numpy as np

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [5]:
a = np.zeros(100)

#### 2.Создать вектор размера 100, заполненный единицами

In [4]:
b = np.ones(100)

#### 3.Создать вектор размера 100, заполненный числом 3

In [8]:
c = np.ones(100) * 3

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [13]:
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 5. Поменять 2 строки в матрице

In [23]:
a = np.random.randint(0, 10, size=(3, 3))
a

array([[5, 6, 4],
       [8, 2, 5],
       [6, 4, 5]])

In [26]:
n = 0
m = 1
a[[n, m]] = a[[m, n]]
a

array([[5, 6, 4],
       [8, 2, 5],
       [6, 4, 5]])

#### 6. Создать вектор со значениями от 10 до 100

In [31]:
b = np.arange(10, 100)

#### 7. Развернуть вектор (первый становится последним)

In [32]:
a = np.arange(10)
np.flip(a)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [35]:
a = np.arange(0, 16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [70]:
a = np.arange(1, 6)
z = np.zeros(3 * len(a)).reshape(len(a), 3)
np.hstack((a.reshape(len(a), 1), z)).reshape(-1)

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.,
       0., 0., 0.])

#### 10. Создать 3x3 единичную матрицу

In [90]:
a = np.eye(3, 3)

#### 11. Создать массив 3x3x3 со случайными значениями

In [78]:
a = np.random.random((3, 3, 3))

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [80]:
a = np.random.random((10, 10))
print(np.max(a))
print(np.min(a))

0.9985652335927172
0.0028450220263253057


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [82]:
a = np.random.random(30)
np.mean(a)

0.49481581347820625

#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [97]:
n = 5
a = np.zeros((n, n))
a[0] = 1
a[n-1] = 1
a[:, 0] = 1
a[:, n-1] = 1
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [101]:
np.row_stack((np.zeros(5), np.column_stack((np.diag([1, 2, 2, 4]), np.zeros(4)))))

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [103]:
a = np.zeros((8, 8))
a[1::2, 1::2] = 1
a[::2, ::2] = 1
a.astype(int)

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [124]:
indices = np.arange(0, 6*7*8).reshape(6, 7, 8)
x, y, z = np.where(indices == 99) # так как отсчет начинается с 0
print(x, y, z)

[1] [5] [3]


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [104]:
row_a = np.tile([1, 0], 4)
a = np.row_stack((row_a, np.flip(row_a)))
a = np.tile(a, (4, 1))
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 24. Есть генератор, сделать с его помощью массив

In [139]:
a = np.fromiter(square(4), dtype=int)
a

array([1, 4, 9])

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [126]:
def square(n):
    for i in range(1, n):
        yield i ** 2

#### 26. Отсортировать вектор

In [163]:
a = np.random.random(10)
a[a == 0] = np.random.random()
a

array([0.86081259, 0.42513397, 0.85222925, 0.84266067, 0.87479073,
       0.7489645 , 0.71555412, 0.956473  , 0.92456249, 0.25186815])

#### 27. Проверить, одинаковы ли 2 numpy массива

In [176]:
a = np.random.random(10)
np.sort(a)
a

array([0.18011319, 0.38352513, 0.45842394, 0.65325475, 0.55596754,
       0.45855582, 0.61024869, 0.16298641, 0.67852339, 0.45787009])

In [190]:
print(np.array_equal(a, b))
print(np.array_equal(b, c))

True
False


#### 28. Сделать массив неизменяемым

In [188]:
a = np.arange(10)
b = np.arange(10)
c = np.random.randint(0, 10, size=(10))

In [193]:
a[1] = 0

ValueError: assignment destination is read-only

#### 29. Найти n наибольших значений в массиве

In [192]:
a = np.arange(10)
a.flags.writeable = False

#### 30. Заменить максимальный элемент на ноль

In [203]:
n = 5
a = np.random.random(10)
np.sort(a)[-n:]

array([0.60222096, 0.87969516, 0.92710925, 0.93994113, 0.95002547])

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [206]:
a[np.argmax(a)] = 0
a

array([0.50532625, 0.58585723, 0.93994113, 0.87969516, 0.22966619,
       0.92710925, 0.02619594, 0.60222096, 0.36120043, 0.        ])

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

#### 34. Напечатать все значения в массиве

#### 35. Найти ближайшее к заданному значению число в заданном массиве

#### 36. Преобразовать массив из float в int

#### 37. Каков эквивалент функции enumerate для numpy массивов?

#### 38. Случайно расположить p элементов в 2D массив

#### 39. Отнять среднее из каждой строки в матрице

#### 40. Отсортировать матрицу по n-ому столбцу

#### 41. Определить, есть ли в 2D массиве нулевые столбцы

#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям