## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [3]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [4]:
a = np.zeros(5)
b = np.zeros((5, 1))
c = np.zeros((10, 2))
d = np.zeros((3, 6, 2))
e = np.zeros((4, 3, 2, 1))
a

array([0., 0., 0., 0., 0.])

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [5]:
a = np.ones(5).astype(int)
b = np.ones((5, 1)).astype(int)
c = np.ones((10, 2)).astype(int)
d = np.ones((3, 6, 2)).astype(int)
e = np.ones((4, 3, 2, 1)).astype(int)
a

array([1, 1, 1, 1, 1])

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [6]:
print("a:", a.size, a.reshape(5, 1).shape, a.reshape(5, 1, 1).shape, a.reshape(5, 1, 1, 1).shape)
print("b:", b.size, b.reshape(1, 5).shape, b.reshape(5, 1, 1).shape, b.reshape(1, 5, 1, 1).shape)
print("c:", c.size, c.reshape(5, 4).shape, c.reshape(2, 10, 1).shape, c.reshape(2, 5, 2, 1).shape)
print("d:", d.size, d.reshape(18, 2).shape, d.reshape(3, 2, 6).shape, d.reshape(3, 2, 3, 2).shape)
print("e:", e.size, e.reshape(12, 2).shape, e.reshape(6, 2, 2).shape, e.reshape(6, 2, 1, 2).shape)

a: 5 (5, 1) (5, 1, 1) (5, 1, 1, 1)
b: 5 (1, 5) (5, 1, 1) (1, 5, 1, 1)
c: 20 (5, 4) (2, 10, 1) (2, 5, 2, 1)
d: 36 (18, 2) (3, 2, 6) (3, 2, 3, 2)
e: 24 (12, 2) (6, 2, 2) (6, 2, 1, 2)


Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [7]:
v = np.random.randint(0, 9, size=(5, 7))
v

array([[8, 5, 0, 2, 6, 6, 5],
       [7, 7, 7, 0, 4, 3, 7],
       [6, 0, 8, 5, 3, 0, 0],
       [2, 4, 1, 5, 0, 1, 7],
       [3, 8, 1, 7, 4, 6, 3]])

In [8]:
print(v.max(axis=1)) # or np.max(v, axis=1)
print(v.min(axis=0))
print(v.sum())
print(v.mean(axis=0))
print(np.median(v, axis=1))

[8 7 8 7 8]
[2 0 0 0 0 0 0]
141
[5.2 4.8 3.4 3.8 3.4 3.2 4.4]
[5. 7. 3. 2. 4.]


Задание 6.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [9]:
print(v.shape)
print(v.shape[0])
print(v.shape[1])

(5, 7)
5
7


Задание 7.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [10]:
print(v[v > 5])
print(np.flip(v[v < 7]))
print(v[(v > 3) & (v % 4 == 0)])
print(v[v % 5 == 3])
print(np.argmax(v))
print(np.argmin(v))
print(np.argsort(v))

[8 6 6 7 7 7 7 6 8 7 8 7 6]
[3 6 4 1 3 1 0 5 1 4 2 0 0 3 5 0 6 3 4 0 5 6 6 2 0 5]
[8 4 8 4 8 4]
[8 3 8 3 3 8 3]
0
2
[[2 3 1 6 4 5 0]
 [3 5 4 0 1 2 6]
 [1 5 6 4 3 0 2]
 [4 2 5 0 1 3 6]
 [2 0 6 4 5 3 1]]


Задание 8.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [11]:
print(v * 3, v / 7, v ** (2/3), np.sin(v), np.log(v), sep="\n")

[[24 15  0  6 18 18 15]
 [21 21 21  0 12  9 21]
 [18  0 24 15  9  0  0]
 [ 6 12  3 15  0  3 21]
 [ 9 24  3 21 12 18  9]]
[[1.14285714 0.71428571 0.         0.28571429 0.85714286 0.85714286
  0.71428571]
 [1.         1.         1.         0.         0.57142857 0.42857143
  1.        ]
 [0.85714286 0.         1.14285714 0.71428571 0.42857143 0.
  0.        ]
 [0.28571429 0.57142857 0.14285714 0.71428571 0.         0.14285714
  1.        ]
 [0.42857143 1.14285714 0.14285714 1.         0.57142857 0.85714286
  0.42857143]]
[[4.         2.92401774 0.         1.58740105 3.30192725 3.30192725
  2.92401774]
 [3.65930571 3.65930571 3.65930571 0.         2.5198421  2.08008382
  3.65930571]
 [3.30192725 0.         4.         2.92401774 2.08008382 0.
  0.        ]
 [1.58740105 2.5198421  1.         2.92401774 0.         1.
  3.65930571]
 [2.08008382 4.         1.         3.65930571 2.5198421  3.30192725
  2.08008382]]
[[ 0.98935825 -0.95892427  0.          0.90929743 -0.2794155  -0.2794155
  -0.958

C:\Users\daris\AppData\Local\Temp/ipykernel_22956/4185158360.py:1: RuntimeWarning: divide by zero encountered in log
  print(v * 3, v / 7, v ** (2/3), np.sin(v), np.log(v), sep="\n")


### Разные инициализации + индексирование (3 балла)

Задание 9.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [12]:
square_odd = np.arange(1, 18, 2).reshape(3, 3)
square_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 10.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [13]:
square_even1 = np.flip(np.arange(0, 32, 2).reshape(4, 4))
square_even2 = np.arange(0, 32, 2)[::-1].reshape(4, 4) # or
print(square_even1 == square_even2) 
square_even1

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


array([[30, 28, 26, 24],
       [22, 20, 18, 16],
       [14, 12, 10,  8],
       [ 6,  4,  2,  0]])

Задание 11.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [14]:
x = np.tile(np.arange(-5, 6), (11, 1))
y = np.rot90(x)

In [15]:
coord = np.flip(np.dstack((x, y))).reshape(11, 11, 2)
coord = np.column_stack(coord).reshape(11, 11, 2) * 0.1
coord

array([[[-0.5,  0.5],
        [-0.4,  0.5],
        [-0.3,  0.5],
        [-0.2,  0.5],
        [-0.1,  0.5],
        [ 0. ,  0.5],
        [ 0.1,  0.5],
        [ 0.2,  0.5],
        [ 0.3,  0.5],
        [ 0.4,  0.5],
        [ 0.5,  0.5]],

       [[-0.5,  0.4],
        [-0.4,  0.4],
        [-0.3,  0.4],
        [-0.2,  0.4],
        [-0.1,  0.4],
        [ 0. ,  0.4],
        [ 0.1,  0.4],
        [ 0.2,  0.4],
        [ 0.3,  0.4],
        [ 0.4,  0.4],
        [ 0.5,  0.4]],

       [[-0.5,  0.3],
        [-0.4,  0.3],
        [-0.3,  0.3],
        [-0.2,  0.3],
        [-0.1,  0.3],
        [ 0. ,  0.3],
        [ 0.1,  0.3],
        [ 0.2,  0.3],
        [ 0.3,  0.3],
        [ 0.4,  0.3],
        [ 0.5,  0.3]],

       [[-0.5,  0.2],
        [-0.4,  0.2],
        [-0.3,  0.2],
        [-0.2,  0.2],
        [-0.1,  0.2],
        [ 0. ,  0.2],
        [ 0.1,  0.2],
        [ 0.2,  0.2],
        [ 0.3,  0.2],
        [ 0.4,  0.2],
        [ 0.5,  0.2]],

       [[-0.5,  0.1],
  

In [46]:
new_coord = [[tuple(i) for i in j] for j in coord]
new_coord

[[(-0.5, 0.5),
  (-0.4, 0.5),
  (-0.30000000000000004, 0.5),
  (-0.2, 0.5),
  (-0.1, 0.5),
  (0.0, 0.5),
  (0.1, 0.5),
  (0.2, 0.5),
  (0.30000000000000004, 0.5),
  (0.4, 0.5),
  (0.5, 0.5)],
 [(-0.5, 0.4),
  (-0.4, 0.4),
  (-0.30000000000000004, 0.4),
  (-0.2, 0.4),
  (-0.1, 0.4),
  (0.0, 0.4),
  (0.1, 0.4),
  (0.2, 0.4),
  (0.30000000000000004, 0.4),
  (0.4, 0.4),
  (0.5, 0.4)],
 [(-0.5, 0.30000000000000004),
  (-0.4, 0.30000000000000004),
  (-0.30000000000000004, 0.30000000000000004),
  (-0.2, 0.30000000000000004),
  (-0.1, 0.30000000000000004),
  (0.0, 0.30000000000000004),
  (0.1, 0.30000000000000004),
  (0.2, 0.30000000000000004),
  (0.30000000000000004, 0.30000000000000004),
  (0.4, 0.30000000000000004),
  (0.5, 0.30000000000000004)],
 [(-0.5, 0.2),
  (-0.4, 0.2),
  (-0.30000000000000004, 0.2),
  (-0.2, 0.2),
  (-0.1, 0.2),
  (0.0, 0.2),
  (0.1, 0.2),
  (0.2, 0.2),
  (0.30000000000000004, 0.2),
  (0.4, 0.2),
  (0.5, 0.2)],
 [(-0.5, 0.1),
  (-0.4, 0.1),
  (-0.30000000000000004, 0

Задание 12.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

Можно с помощью индексирования:

In [17]:
a = np.zeros((8, 8))
a[1::2, 1::2] = 1
a[::2, ::2] = 1
a.astype(int)

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

Либо используя tile

In [18]:
row_a = np.tile([1, 0], 4)
a = np.row_stack((row_a, np.flip(row_a)))
a = np.tile(a, (4, 1))
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

Задание 13.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [19]:
a = np.ones((8, 8))
a[1::2, 1::2] = 0
a[::2, ::2] = 0
a.astype(int)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [20]:
row_a = np.tile([0, 1], 4)
a = np.row_stack((row_a, np.flip(row_a)))
a = np.tile(a, (4, 1))
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Задание 14.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [21]:
n = 5
a = np.ones((n, n))

In [22]:
np.tril(a)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

Задание 15.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [23]:
np.triu(a)

array([[1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.]])

Задание 16.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [24]:
a = np.zeros((n, n))
a[np.diag_indices_from(a)] = 1
a = np.rot90(a)
a

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

### Операции + аггрегации (3 балла)

Задание 17.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [25]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [26]:
def expected_value_np(x):
    return np.mean(x)

In [27]:
def dispersion_np(x):
    return np.std(x) ** 2

In [28]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [29]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [30]:
def mean_square_difference_np(y1, y2):
    return np.mean((y1 - y2) ** 2)

In [31]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [32]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [33]:
def mean_abs_difference_np(y1, y2):
    return np.mean(np.abs(y1 - y2))

In [34]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 20.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [35]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [36]:
def matching_proba_np(y1, y2):
    return len(y1[y1 == y2])/len(y1)

In [37]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 21.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

* Необходимо найти границы (индексы), такие, что если мы разделим какой-то из них оба вектора, то в левой части пересекающихся в $y_1$ и $y_2$ нулей будет больше, чем единиц, а в правой - наоборот. Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [38]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [39]:
def find_thresholds_np(y1, y2):
    n = y1.shape
    match_zeros = np.zeros(n)
    match_zeros[(y1 == y2) & (y2 == 0)] = 1
    
    match_ones = np.zeros(n)
    match_ones[(y1 == y2) & (y2 == 1)] = 1
    
    res = np.array(np.where(
        (np.sum(np.tril(match_zeros), axis=1)[:-1] / np.arange(1, n[0]) > 0.5) &
        (np.sum(np.triu(match_ones), axis=1)[1:] / np.flip(np.arange(1, n[0])) > 0.5))) + 1
    
    if np.sum(match_ones) / n > 0.5:
        res = np.append(res, 0)
    elif np.sum(match_zeros) / n > 0.5:
        res = np.append(res, n)

    return np.array(res).squeeze()

In [40]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 22.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно пяти** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [41]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

# (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
# data = np.resize(data, (32, 1))
data = data.reshape((32, 3, 16*16))
n = np.random.randint(0, 10, size=(16*16, 1))
data = np.dot(data, n).squeeze()
d = np.random.randint(0, 10, size=(3, 1))
data = np.dot(data, d)

assert data.shape == (32, 1)

Задание 23.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [42]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

# (∩｀-´)⊃━☆ﾟ.*･｡ﾟ !!!magic!!!
a = np.hstack((np.dot(m2, W2), np.dot(m2, W2)))
b = np.dot(m1, W1)
result = a * b

assert result.shape == (32, 32)

Задание 24.

Последнее испытание для юного мага матриц - приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [43]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ

# можно так
# result = np.resize(np.clip(result, 0, 1), (32, 3))

# можно и так
temp = np.random.randint(0, 10, size=(32, 3))
result = np.clip(np.dot(result, temp), 0, 1)

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()